remove script that breaks
ah hahaha
when you stare into the abyss, the abyss stares into you

$ bin/console doctrine:database:create
Could not create database /builds/kush/symfony-demo/var/data/blog.sqlite for connection named default
An exception occurred in driver: SQLSTATE[HY000] [14] unable to open database file
ERROR: Job failed: exit code 1

https://gitlab.com/kush/symfony-demo/-/jobs/89372944