use yarn add
$ yarn install node-sass
yarn install v1.9.4
error `install` has been replaced with `add` to add new dependencies. Run "yarn add node-sass" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1